website/apps/share_links/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.utils.translation import gettext_lazy as _
from django_comments.feeds import LatestCommentFeed

from . import views

urlpatterns = [
    # search
    path(_("search/"), views.SearchView.as_view(), name="search"),
    # rss
    path(_("rss/"), views.RSSView.as_view(), name="rss_index"),
    path(_("rss/new/all/"), views.RSSNewView(), name="rss_new"),
    path(_("rss/new/links/"), views.RSSNewLinksView(), name="rss_new_links"),
    path(_("rss/new/tags/"), views.RSSNewTagsView(), name="rss_new_new_tags"),
    path("rss/latest-comments/", LatestCommentFeed()),
    # misc
    path(_("about/"), views.AboutView.as_view(), name="about"),
    path(_("contact/"), views.ContactView.as_view(), name="contact"),
    path(_("statistics/"), views.StatsView.as_view(), name="stats"),
    path(_("webring/"), views.WebRingView.as_view(), name="webring"),
    # smol api
    path(_("get-title/"), login_required(views.get_title_view), name="get_title"),
    path(_("get-lang/"), login_required(views.get_lang_view), name="get_lang"),
    # tags
    path(_("tag/<str:slug>/"), views.TagView.as_view(), name="tag"),
    path(_("tags/"), views.TagsView.as_view(), name="tags"),
    path(_("category/<int:pk>/"), views.CategoryView.as_view(), name="category"),
    # Comments
    # path(_("last-comments/"), views.LastCommentsView.as_view(), name="comments"),
    # collections
    path(
        _("collection/<str:slug>/"), views.CollectionView.as_view(), name="collection"
    ),
    path(_("collections/"), views.CollectionsView.as_view(), name="collections"),
    # links
    path(_("link/<int:pk>/"), views.LinkView.as_view(), name="link"),
    path(
        _("domain-name/<str:domain_name>/"),
        views.LinkIndexView.as_view(),
        name="link_index",
    ),
    path(_("random/"), views.go_random_link, name="random"),
    path("", views.LinksView.as_view(), name="homepage"),
]

website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(f"{settings.DJANGO_ADMIN_URL}/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is True:
    urlpatterns = urlpatterns + [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

urlpatterns += i18n_patterns(
    path("comments/", include("django_comments.urls")),
    path("", include("website.apps.share_links.urls")),
)

website/apps/share_links/models.py
from django.conf import settings
from django.conf.global_settings import LANGUAGES as FULL_LANGUAGES_LIST
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django_comments.moderation import CommentModerator, moderator
from parler.models import TranslatableModel, TranslatedFields, TranslationDoesNotExist

from website.apps.share_links_comments.models import CommentwithCaptcha


class Link(TranslatableModel):
    link = models.CharField(_("Link"), max_length=2000, unique=True)
    translations = TranslatedFields(
        title=models.CharField(_("Title"), max_length=2000, null=True, blank=True),
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_("You can use markdown here."),
        ),
    )
    tags = models.ManyToManyField(to="Tag", related_name="links", blank=True)
    highlight = models.BooleanField(
        default=False,
        blank=True,
        help_text=_(
            'Link will be displayed with a special color, and will appear in the "highlighted" sort option.'
        ),
    )
    date_added = models.DateTimeField(auto_now_add=True, blank=True)
    file = models.FileField(
        upload_to="files/",
        null=True,
        blank=True,
        help_text=_(
            f"Upload pdf or screenshot of the page. If this field is empty and USE_WEASYPRINT is set to True (currently set to {settings.USE_WEASYPRINT}), then the pdf will be auto-generated using weasyprint."
        ),
    )
    save_file = models.BooleanField(
        default=True,
        help_text=_(
            "Uncheck this box if you don't want the file to be auto-generated."
        ),
    )
    online = models.BooleanField(
        default=True,
        help_text=_(
            "Uncheck this box if the link is not online anymore (will provide the web archive link instead of the original link)."
        ),
    )
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )
    language = models.CharField(
        verbose_name=_("Language"),
        choices=FULL_LANGUAGES_LIST,
        max_length=7,
        null=True,
        blank=True,
    )
    allow_override_title = models.BooleanField(
        verbose_name=_("Allow override title?"),
        help_text=_(
            "Management commands will try to fetch the title from the website &lt;title&gt; tag."
        ),
        default=False,
    )
    allow_override_language = models.BooleanField(
        verbose_name=_("Allow override language?"),
        help_text=_(
            "Management commands will try to fetch the language from the lang attribute."
        ),
        default=False,
    )
    comments = GenericRelation(to=CommentwithCaptcha, object_id_field="object_pk")

    class Meta:
        verbose_name = _("Link")
        verbose_name_plural = _("Links")

    def __str__(self):
        try:
            return f"{self.title} ({self.link})"
        except TranslationDoesNotExist:
            return f"{self.link}"

    def save(self, *args, **kwargs):
        if settings.USE_WEASYPRINT and not self.file and self.save_file:
            from re import compile

            from django.core.files.base import ContentFile
            from weasyprint import HTML

            url_format = compile(r"https?://(www\.)?")
            file_name = (
                url_format.sub("", self.link).strip().strip("/").replace("/", "_")
                + ".pdf"  # noqa
            )

            pdf = HTML(self.link).write_pdf()
            pdf = ContentFile(pdf)

            self.file.save(file_name, pdf, save=False)

        super().save(*args, **kwargs)


class EntryModerator(CommentModerator):
    email_notification = False


moderator.register(Link, EntryModerator)


class Category(TranslatableModel):
    translations = TranslatedFields(
        label=models.CharField(_("Label"), max_length=2048),
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_("You can use markdown here."),
        ),
    )

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.label


class Tag(TranslatableModel):
    translations = TranslatedFields(
        tag=models.CharField(_("Tag"), max_length=2000),
        slug=models.SlugField(_("Slug"), max_length=2000, allow_unicode=True),
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_("You can use markdown here."),
        ),
    )
    category = models.ForeignKey(
        to=Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    highlight = models.BooleanField(
        default=False,
        blank=True,
        help_text=_(
            'Tag will be displayed with a special color, and will appear in the "highlighted" sort option.'
        ),
    )
    date_added = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return f"{self.tag}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.tag)
        super().save(*args, **kwargs)


@receiver(pre_save, sender=Tag)
def pre_save_for_categories_and_tags_fixture(sender, instance, **kwargs):
    if kwargs["raw"]:
        instance.date_added = timezone.now()


class AboutContactPages(TranslatableModel):
    translations = TranslatedFields(
        page_title=models.CharField(_("Title"), max_length=255, blank=True, null=True),
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_("You can use markdown here."),
        ),
    )

    def __str__(self):
        return f"{str(self.id)} − {self.page_title}"

    class Meta:
        verbose_name = _("About & Contact Pages")
        verbose_name_plural = _("About & Contact Pages")


class Collection(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(
            _("Name"),
            max_length=1024,
            help_text=_("The name of the collection."),
        ),
        slug=models.SlugField(_("Slug"), max_length=2000, editable=False, unique=True),
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_("You can use markdown here."),
        ),
    )
    date_added = models.DateTimeField(auto_now_add=True, blank=True)
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )
    highlight = models.BooleanField(
        default=False,
        blank=True,
        help_text=_(
            'Collection will be displayed with a special color, and will appear in the "highlighted" sort option.'
        ),
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class CollectionLink(TranslatableModel):
    translations = TranslatedFields(
        description=models.TextField(
            _("Description"),
            blank=True,
            null=True,
            help_text=_(
                "You can use markdown here. If the description is empty, the link description will be used (if it exists)."
            ),
        )
    )
    link = models.ForeignKey("Link", on_delete=models.CASCADE)
    collection = models.ForeignKey("Collection", on_delete=models.CASCADE)

    def __str__(self):
        if self.link.title:
            return self.link.title
        return self.link.link

website/apps/share_links/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class SearchForm(forms.Form):
    search = forms.CharField(label=_("Search"), max_length=255)

website/apps/share_links/templates/share_links/partials/category.html
{% load markdownify i18n humanize %}

<article>
  <h2><a href="{% url "category" category.pk %}">{{ category.label }}</a></h2>
</p>
{% if category.description %}
  <p>
    {{ category.description|markdownify|truncatewords_html:20 }}
  </p>
{% endif %}
</article>

website/apps/share_links/templates/share_links/partials/collection.html
{% load share_links_templatetags markdownify i18n humanize %}

<article>
  <h2><a href="{% url "collection" collection.slug %}">{{ collection.name }}</a></h2>
  <p class="opacity" title="{{ collection.date_added }}">
    {{ collection.date_added|naturaltime }}</span> &mdash;
  <i>
    {{ collection.collectionlink_set.all|length }} {% translate "link" %}{{ collection.collectionlink_set.all|length|pluralize }}
    {% if collection.added_by %}
      &mdash; {% translate "Added by" %} <a href="/{{ LANGUAGE_CODE }}/?sort=author&author={{ collection.added_by.username }}">{{ collection.added_by.username }}</a>
    {% endif %}
  </i>
</p>
</p>
{% if collection.description %}
  <p>
    {{ collection.description|markdownify|truncatewords_html:20 }}
  </p>
{% endif %}
</article>

website/apps/share_links/templates/share_links/partials/collectionlink.html
{% extends "share_links/link/link.html" %}
{% load markdownify %}


{% block description %}
  {% if description %}
    <p class="serif">
      {% if page_obj or request.GET.search %}
        {{ description|markdownify|truncatewords_html:20 }}
      {% else %}
        {{ description|markdownify }}
      {% endif %}
    </p>
  {% else %}
    <p class="serif">
      {% if page_obj or request.GET.search %}
        {{ link.description|markdownify|truncatewords_html:20 }}
      {% else %}
        {{ link.description|markdownify }}
      {% endif %}
    </p>
  {% endif %}
{% endblock %}

website/apps/share_links/templates/share_links/partials/pagination.html
{% load share_links_templatetags i18n %}

{% block pagination %}
  <aside class="pagination">
    {% if page_obj.has_previous %}
      <a href="?{% query_transform page=1 %}">&laquo; {% translate "first" %}</a>
      <a href="?{% query_transform page=page_obj.previous_page_number %}">{% translate "previous" %}</a>
    {% endif %}
    <p>{% blocktranslate with current=page_obj.number total=page_obj.paginator.num_pages %}Page {{ current }} of {{ total }}{% endblocktranslate %}</p>
    {% if page_obj.has_next %}
      <a href="?{% query_transform page=page_obj.next_page_number %}">{% translate "next" %}</a>
      <a href="?{% query_transform page=page_obj.paginator.num_pages %}">{% translate "last" %} &raquo;</a>
    {% endif %}
  </span>
  </aside>
{% endblock %}

website/apps/share_links/templates/share_links/partials/sort.html
{% load i18n %}

<nav>
  <form action="" method="get">
    <div id="filters-menu">
      {{ filter.form.as_p }}
    </div>
    <input type="submit" value="{% translate 'Apply filters' %}" />
  </form>
</nav>

website/apps/share_links/templates/share_links/partials/tag.html
{% load share_links_templatetags markdownify i18n humanize %}

<article>
  <h2><a href="{% url "tag" tag.slug %}">{{ tag.tag }}</a></h2>
  <p class="opacity">{% if tag.category %}{% translate "Subcategory of" %} <a href="{% url 'category' tag.category.pk %}">{{ tag.category }}</a> &mdash;{% endif %}<span title="{{ tag.date_added }}">{{ tag.date_added|naturaltime }}</span> &mdash; {{ tag|get_links_nb }} {% translate "link" %}{{ tag|get_links_nb|pluralize }}</span>
</p>
{% if tag.description %}
  <p>
    {{ tag.description|markdownify|truncatewords_html:20 }}
  </p>
{% endif %}
</article>